(function () {
  'use strict';

  function item(data) { return data; }

  window.PALEOZOIC_ORGANISMS = {
    marrella: item({ name: 'Marrella', scientific: 'Marrella splendens', group: ['Arthropoda', 'Marrellomorpha'], description: 'A tiny, delicate arthropod and one of the most abundant animals of the Burgess Shale. Marrella moved close to the seafloor, gathering fine organic material from the sediment and surrounding water.', size: 'Up to ~2.5 cm', depth: 'Near the marine seafloor', diet: 'Fine organic particles', dietType: 'Deposit feeder / suspension feeder', habitat: 'Soft-bottom marine environment', behavior: 'Mobile near-bottom swimmer', period: 'Middle Cambrian', age: '~505 million years ago', found: 'Burgess Shale, British Columbia, Canada', tags: ['ARTHROPOD', 'BENTHIC', 'COMMON'], era: 'cambrian', image: '../asset-pipeline/organism_renders/marrella.jpg' }),
    vauxia: item({ name: 'Vauxia', scientific: 'Vauxia gracilenta', group: ['Porifera', 'Demospongiae'], description: 'A branching Cambrian sponge that grew upright from the seafloor. Water flowed through its porous body, allowing it to filter microscopic organisms and organic particles from the surrounding water.', size: 'Up to ~8 cm tall', depth: 'Marine seafloor', diet: 'Suspended microorganisms and organic particles', dietType: 'Filter feeder', habitat: 'Sponge-rich seafloor communities', behavior: 'Sessile', period: 'Middle Cambrian', age: '~505 million years ago', found: 'Burgess Shale region, British Columbia, Canada', tags: ['SPONGE', 'FILTER FEEDER', 'SESSILE'], era: 'cambrian', image: '../asset-pipeline/organism_renders/vauxia.jpg' }),
    gogia: item({ name: 'Gogia', scientific: 'Gogia stephenensis', group: ['Echinodermata', 'Gogiida'], description: 'A stalked Cambrian echinoderm with a plated, vase-shaped body and branching feeding appendages called brachioles. It anchored itself to the seafloor and captured tiny food particles carried by the current.', size: 'Several centimeters tall', depth: 'Marine seafloor', diet: 'Suspended organic particles', dietType: 'Suspension feeder', habitat: 'Soft-bottom marine environment', behavior: 'Sessile, attached feeder', period: 'Middle Cambrian', age: '~505 million years ago', found: 'Burgess Shale, British Columbia, Canada', tags: ['ECHINODERM', 'SESSILE', 'FILTER FEEDER'], era: 'cambrian', image: '../asset-pipeline/organism_renders/dinomischus.jpg' }),
    opabinia: item({ name: 'Opabinia', scientific: 'Opabinia regalis', group: ['Panarthropoda', 'Opabiniidae'], description: "One of the Cambrian's strangest animals, Opabinia had five eyes, lateral swimming flaps and a long flexible proboscis ending in a grasping structure. It likely used the proboscis to collect small prey from near the seafloor.", size: 'Up to ~10 cm', depth: 'Near the marine seafloor', diet: 'Small animals', dietType: 'Predator', habitat: 'Soft-bottom marine environment', behavior: 'Active near-bottom swimmer', period: 'Middle Cambrian', age: '~505 million years ago', found: 'Burgess Shale, British Columbia, Canada', tags: ['PREDATOR', 'SWIMMER', 'PANARTHROPOD'], era: 'cambrian', image: '../asset-pipeline/organism_renders/opabinia.jpg' }),
    hallucigenia: item({ name: 'Hallucigenia', scientific: 'Hallucigenia sparsa', group: ['Panarthropoda', 'Lobopodia'], description: 'A tiny worm-like animal protected by pairs of long dorsal spines. Hallucigenia walked across the seabed on soft clawed legs and was frequently associated with Cambrian sponge communities.', size: '~1–3 cm', depth: 'Marine seafloor', diet: 'Small organic particles; exact diet uncertain', dietType: 'Suspension / selective feeder', habitat: 'Sponge-rich seabed', behavior: 'Slow bottom crawler', period: 'Middle Cambrian', age: '~505 million years ago', found: 'Burgess Shale, British Columbia, Canada', tags: ['LOBOPODIAN', 'SPINY', 'BENTHIC'], era: 'cambrian', image: '../asset-pipeline/organism_renders/hallucigenia.jpg' }),
    hurdia: item({ name: 'Hurdia', scientific: 'Hurdia victoria', group: ['Arthropoda', 'Radiodonta · Hurdiidae'], description: 'A large radiodont relative of Anomalocaris with a distinctive three-part head shield and rake-like frontal appendages. Hurdia probably cruised just above the seabed and swept small animals and other food toward its circular mouth.', size: '~20–30 cm', depth: 'Near the marine seafloor', diet: 'Small benthic animals', dietType: 'Predator / benthic forager', habitat: 'Open marine seabed', behavior: 'Active nektobenthic swimmer', period: 'Middle Cambrian', age: '~505 million years ago', found: 'Burgess Shale, British Columbia, Canada', tags: ['RADIODONT', 'PREDATOR', 'SWIMMER'], era: 'cambrian', image: '../asset-pipeline/organism_renders/hurdia_victoria.jpg' }),
    treptoceras: item({ name: 'Treptoceras', scientific: 'Treptoceras duseri', group: ['Mollusca', 'Cephalopoda · Orthocerida'], description: 'A small straight-shelled cephalopod with a long chambered shell. Its head and arms projected from the open end while the internal chambers helped control buoyancy.', size: '~20 cm typical', depth: 'Shallow marine shelf', diet: 'Small marine animals', dietType: 'Carnivore', habitat: 'Open Ordovician seas', behavior: 'Mobile cephalopod', period: 'Late Ordovician', age: '~450 million years ago', found: 'Especially well known from Ohio, Kentucky and Indiana, USA', tags: ['CEPHALOPOD', 'ORTHOCONE', 'CARNIVORE'], era: 'ordovician', image: '../asset-pipeline/organism_renders/treptoceras.jpg' }),
    endoceras: item({ name: 'Endoceras', scientific: 'Endoceras sp.', group: ['Mollusca', 'Cephalopoda · Endocerida'], description: 'A giant straight-shelled cephalopod and one of the largest animals in Ordovician seas. Its enormous chambered shell controlled buoyancy while the head and arms projected from the shell opening.', size: 'Several meters; giant forms ~3–5+ m', depth: 'Near-bottom marine waters', diet: 'Marine animals', dietType: 'Carnivore', habitat: 'Continental shelf seas', behavior: 'Nektobenthic predator', period: 'Middle–Late Ordovician', age: '~470–444 million years ago', found: 'North America, Europe and other Ordovician marine deposits', tags: ['GIANT', 'CEPHALOPOD', 'PREDATOR'], era: 'ordovician', image: '../asset-pipeline/organism_renders/endoceras.jpg' }),
    trilobiteOrdovician: item({ name: 'Trilobite', scientific: 'Trilobita', group: ['Arthropoda', 'Trilobita'], description: 'Armored marine arthropods with segmented bodies divided lengthwise into three lobes. Trilobites reached enormous diversity during the Ordovician and occupied ecological roles ranging from deposit feeding to active predation.', size: 'Typically a few centimeters; highly variable', depth: 'Marine seafloor', diet: 'Detritus, organic particles or small animals', dietType: 'Deposit feeder / scavenger / predator', habitat: 'Shallow and deeper marine seabeds', behavior: 'Bottom crawler', period: 'Ordovician', age: '~486–444 million years ago', found: 'Marine deposits worldwide', tags: ['ARTHROPOD', 'ARMORED', 'BENTHIC'], era: 'ordovician', image: '../asset-pipeline/organism_renders/trilobite.jpg' }),
    bryozoansOrdovician: item({ name: 'Bryozoans', scientific: 'Bryozoa', group: ['Bryozoa'], description: 'Colonial filter-feeding animals composed of hundreds or thousands of tiny individuals called zooids. During the Ordovician they became increasingly important components of marine seafloor communities.', size: 'Microscopic zooids; colonies several centimeters or larger', depth: 'Marine seafloor', diet: 'Plankton and suspended organic particles', dietType: 'Suspension feeder', habitat: 'Reefs and firm seafloor surfaces', behavior: 'Sessile colonial organism', period: 'Ordovician', age: '~486–444 million years ago', found: 'Marine deposits worldwide', tags: ['COLONIAL', 'FILTER FEEDER', 'BENTHIC'], era: 'ordovician', image: '../asset-pipeline/organism_renders/bryozoans.jpg' }),
    pentecopterus: item({ name: 'Pentecopterus', scientific: 'Pentecopterus decorahensis', group: ['Arthropoda', 'Chelicerata · Eurypterida'], description: 'One of the earliest well-known sea scorpions. Pentecopterus was a large predatory arthropod with a streamlined body and spiny limbs adapted for capturing prey, showing that eurypterids had already become formidable predators during the Ordovician.', size: 'Up to ~1.7 m estimated', depth: 'Shallow aquatic environment', diet: 'Small aquatic animals', dietType: 'Predator', habitat: 'Shallow marine or marginal marine waters', behavior: 'Active predator / bottom walker', period: 'Middle Ordovician', age: '~467 million years ago', found: 'Iowa, USA', tags: ['EURYPTERID', 'PREDATOR', 'ARTHROPOD'], era: 'ordovician', image: '../asset-pipeline/organism_renders/ordovician_eurypterid.jpg' }),
    trilobiteSilurian: item({ name: 'Trilobite', scientific: 'Trilobita', group: ['Arthropoda', 'Trilobita'], description: 'Armored marine arthropods with a characteristic segmented three-lobed body. Silurian trilobites survived the end-Ordovician mass extinction and continued to occupy the seafloor as scavengers, deposit feeders and predators.', size: 'Typically a few centimeters; highly variable', depth: 'Marine seafloor', diet: 'Detritus, carrion or small animals', dietType: 'Deposit feeder / scavenger / predator', habitat: 'Marine seabed', behavior: 'Bottom crawler', period: 'Silurian', age: '~444–419 million years ago', found: 'Marine deposits worldwide', tags: ['ARTHROPOD', 'ARMORED', 'BENTHIC'], era: 'silurian', image: '../asset-pipeline/organism_renders/trilobite.jpg' }),
    bryozoansSilurian: item({ name: 'Bryozoans', scientific: 'Bryozoa', group: ['Bryozoa'], description: 'Colonial animals consisting of hundreds or thousands of microscopic zooids. Each zooid extended a crown of tentacles into the water to capture suspended food particles.', size: 'Microscopic zooids; colonies centimeters or larger', depth: 'Marine seafloor', diet: 'Plankton and suspended organic particles', dietType: 'Suspension feeder', habitat: 'Reefs and firm seabed surfaces', behavior: 'Sessile colonial organism', period: 'Silurian', age: '~444–419 million years ago', found: 'Marine deposits worldwide', tags: ['COLONIAL', 'FILTER FEEDER', 'REEF'], era: 'silurian', image: '../asset-pipeline/organism_renders/bryozoans.jpg' }),
    pterygotus: item({ name: 'Pterygotus', scientific: 'Pterygotus sp.', group: ['Arthropoda', 'Chelicerata', 'Eurypterida'], description: 'A large predatory eurypterid, or “sea scorpion,” with powerful grasping appendages and paddle-like swimming limbs. Pterygotus was one of the dominant aquatic predators of Silurian coastal waters.', size: 'Up to ~1.5–1.7 m', depth: 'Shallow marine and coastal waters', diet: 'Fish and other aquatic animals', dietType: 'Predator', habitat: 'Shallow seas and coastal environments', behavior: 'Active swimming predator', period: 'Silurian', age: 'Mainly Middle–Late Silurian', found: 'Europe and North America', tags: ['SEA SCORPION', 'PREDATOR', 'EURYPTERID'], era: 'silurian', image: '../asset-pipeline/organism_renders/pterygotus.jpg' }),
    birkenia: item({ name: 'Birkenia', scientific: 'Birkenia elegans', group: ['Chordata', 'Anaspida'], description: 'A small streamlined jawless fish covered in rows of tiny scales. Unlike heavily armored jawless fishes, Birkenia had a relatively flexible body suited to active swimming.', size: 'Up to ~10 cm', depth: 'Shallow aquatic environment', diet: 'Tiny food particles; exact feeding ecology uncertain', dietType: 'Likely microphagous', habitat: 'Coastal marine waters', behavior: 'Active swimmer', period: 'Silurian', age: 'Middle–Late Silurian', found: 'Best known from Scotland and other northern European deposits', tags: ['JAWLESS FISH', 'VERTEBRATE', 'SWIMMER'], era: 'silurian', image: '../asset-pipeline/organism_renders/birkenia.jpg' }),
    crinoid: item({ name: 'Crinoid', scientific: 'Crinoidea', group: ['Echinodermata', 'Crinoidea'], description: 'A stalked echinoderm related to modern sea stars. Its body was raised above the seabed on a stem while a crown of feather-like arms captured plankton and organic particles from passing currents.', size: 'Commonly tens of centimeters; varies widely', depth: 'Marine seafloor', diet: 'Plankton and suspended organic particles', dietType: 'Suspension feeder', habitat: 'Reefs and open seabeds', behavior: 'Sessile suspension feeder', period: 'Silurian', age: '~444–419 million years ago', found: 'Marine deposits worldwide', tags: ['ECHINODERM', 'FILTER FEEDER', 'STALKED'], era: 'silurian', image: '../asset-pipeline/organism_renders/crinoid.jpg' }),
    favosites: item({ name: 'Favosites', scientific: 'Favosites sp.', group: ['Cnidaria', 'Anthozoa · Tabulata'], description: 'A colonial tabulate coral commonly called honeycomb coral because of its tightly packed polygonal skeletal tubes. Each tube housed an individual polyp that captured tiny food particles from the water.', size: 'Colonies several centimeters to tens of centimeters across or larger', depth: 'Shallow marine reef', diet: 'Plankton and suspended organic particles', dietType: 'Suspension feeder', habitat: 'Warm shallow reefs', behavior: 'Sessile colonial reef builder', period: 'Silurian', age: '~444–419 million years ago', found: 'Silurian reef deposits worldwide', tags: ['CORAL', 'COLONIAL', 'REEF BUILDER'], era: 'silurian', image: '../asset-pipeline/organism_renders/favosites.jpg' }),
    rhynia: item({ name: 'Rhynia', scientific: 'Rhynia gwynne-vaughanii', group: ['Tracheophyta', 'Rhyniaceae'], description: 'A simple early vascular plant with upright, leafless stems that repeatedly forked. It lacked true leaves and reproduced through spore-producing structures at the ends of its shoots.', size: '~15–20 cm tall', depth: 'Damp terrestrial ground', diet: 'Photosynthesis', dietType: 'Autotroph', habitat: 'Wet soils around springs and shallow pools', behavior: 'Upright spore-producing plant', period: 'Early land-plant scene', age: '~407 million years ago for R. gwynne-vaughanii', found: 'Rhynie Chert, Scotland', tags: ['EARLY LAND PLANT', 'VASCULAR', 'SPORE-BEARING'], era: 'devonian', image: '../asset-pipeline/organism_renders/rhynia.jpg', nutrition: true }),
    prototaxites: item({ name: 'Prototaxites', scientific: 'Prototaxites sp.', group: ['Eukaryota', 'uncertain affinity'], description: 'A bizarre column-shaped terrestrial organism that towered above the tiny vegetation of early Paleozoic landscapes. Its body consisted of dense networks of microscopic tubes, but exactly what kind of organism it represented remains unresolved.', size: 'Later giant forms reached several meters tall', depth: 'Terrestrial', diet: 'Uncertain', dietType: 'Probably heterotrophic, but unresolved', habitat: 'Early terrestrial ecosystems', behavior: 'Sessile upright organism', period: 'Late Silurian–Devonian range', age: 'Present by roughly ~420 million years ago', found: 'North America and Europe, among other regions', tags: ['GIANT', 'TERRESTRIAL', 'ENIGMATIC'], era: 'silurian', image: '../asset-pipeline/organism_renders/prototaxites.jpg', nutrition: true })
  };

  window.PALEOZOIC_ANNOTATIONS = [
    ['scene4', 0.78730458, 0.33459446, 'marrella'],
    ['scene4', -2.68, 0.29050889, 'vauxia'],
    ['scene4', -2.5855494, -0.02688785, 'gogia'],
    ['scene5', -0.23464541, 0.06998292, 'opabinia'],
    ['scene5', 0.39018206, 0.05807745, 'hallucigenia'],
    ['scene6', 0.30130803, -0.46750331, 'treptoceras'],
    ['scene6', -0.74693435, 0.36195183, 'endoceras'],
    ['scene7', 0.6622447, 1.43089078, 'trilobiteOrdovician'],
    ['scene7', 1.30777971, 0.72580416, 'bryozoansOrdovician'],
    ['scene7', 0.53251403, -0.8541191, 'pentecopterus'],
    ['scene8', 2.87927593, -0.29398892, 'prototaxites'],
    ['scene8', -1.54287435, -0.0372063, 'rhynia'],
    ['scene9', -0.75765323, -0.29361053, 'birkenia'],
    ['scene9', 2.28375413, 0.0419586, 'crinoid'],
    ['scene9', 0.80650724, 0.6365521, 'favosites'],
    ['scene9', 2.4165355, -0.77049524, 'pterygotus']
  ];
}());
