window.EGYPT_EXPLORER = {
  scenes: [
    { id: 'scene1', file: 'panoramas/Scene1-DesertNight.jpg', title: 'Ancient Egypt', description: 'Travel to the beginning of the Old Kingdom, when communities along the Nile were drawn together under the first pharaohs.' },
    { id: 'scene2', file: 'panoramas/Scene2-Canal-hr.jpg', title: 'The Lifeblood of Egypt', description: 'The Nile supplied water, fertile soil, transport, food, and a rhythm that shaped daily life.' },
    { id: 'scene3', file: 'panoramas/Scene3-Market.jpg', title: 'Along the River', description: 'Markets and river traffic connected farms, workshops, and growing settlements throughout the kingdom.' },
    { id: 'scene4', file: 'panoramas/Scene4-Town.jpg', title: 'City Life', description: 'Egyptian towns were busy communities of homes, workshops, temples, and local markets.' },
    { id: 'scene5', file: 'panoramas/Scene5-slaughterhouse.jpg', title: 'A Recorded Life', description: 'Tomb paintings and wooden models preserve detailed scenes of the work people performed each day.' },
    { id: 'scene6', file: 'panoramas/Scene6Weavers.jpg', title: 'The Weavers', description: 'Skilled craftspeople spun fibers and wove linen for clothing, trade, temple offerings, and burial rituals.' },
    { id: 'scene7', file: 'panoramas/Scene7-mummification.jpg', title: 'The Journey After Death', description: 'Mummification was part of a larger set of beliefs about preserving the body and preparing the soul for the afterlife.' },
    { id: 'scene8', file: 'panoramas/Scene8-Palace.jpg', title: 'A Colorful Egypt', description: 'Temples, palaces, and statues were once covered in brilliant pigments rather than bare sandstone.' },
    { id: 'scene9', file: 'panoramas/Scene9-Pyramids.jpg', title: 'The Age of the Pyramids', description: 'The Old Kingdom saw extraordinary experiments in architecture, organization, and engineering.' },
    { id: 'scene10', file: 'panoramas/Scene10-Samurai.jpg', title: 'Until Next Time', description: 'Our journey ends here, but the civilization along the Nile continued to change for thousands of years.' }
  ],
  stories: {
    ra: { scene: 'scene1', yaw: -34, pitch: 4, title: 'The Sun God, Ra', kicker: 'Religion', image: 'story-images/Scene1-Ra.jpg', body: 'Ra was the god of the sun and one of ancient Egypt’s most important deities. Egyptians imagined his daily journey across the sky as part of the cycle of life, death, and renewal.' },
    nile: { scene: 'scene2', yaw: 18, pitch: -5, title: 'The Nile', kicker: 'Landscape', image: 'story-images/Evening,_Nile_River,_Uganda.jpg', body: 'Every year the Nile flooded and left fertile soil along its banks. The river also served as a highway, carrying people, stone, crops, and ideas through the kingdom.' },
    sobek: { scene: 'scene2', yaw: 112, pitch: -10, title: 'Crocodiles and Sobek', kicker: 'Religion & wildlife', image: 'story-images/Scene2-Sobek.jpg', body: 'Crocodiles lived in the Nile and inspired both fear and reverence. Sobek, a powerful crocodile-headed god, was associated with the river, strength, and protection.' },
    papyrus: { scene: 'scene3', yaw: -42, pitch: -8, title: 'Papyrus and Writing', kicker: 'Recorded history', image: 'story-images/Scene3-Papyrus.jpg', body: 'Writing helped Egyptian society manage trade, taxes, religion, and government. Papyrus sheets gave scribes a light, portable surface for preserving records.' },
    fruit: { scene: 'scene3', yaw: 48, pitch: -13, title: 'Fruits of Egypt', kicker: 'Daily life', image: 'story-images/Scene3-Pomegranates.jpg', body: 'Dates, figs, grapes, and pomegranates were eaten and traded in ancient Egypt. Market scenes give us a glimpse of the foods that appeared in everyday life.' },
    osiris: { scene: 'scene4', yaw: -98, pitch: 1, title: 'Isis and Osiris', kicker: 'Mythology', image: 'story-images/Scene4-IsisOsiris.jpg', body: 'The story of Isis restoring Osiris was one of Egypt’s most enduring myths. It connected kingship and family with death, restoration, and the promise of an afterlife.' },
    slaughter: { scene: 'scene5', yaw: 27, pitch: -9, title: 'A Recorded Workplace', kicker: 'Daily life', image: 'story-images/Scene5-HieroglyphSlaughterhouse.jpg', body: 'Scenes of butchers at work were recorded in tomb art. Such images are valuable evidence for the tools, tasks, and organization of ancient Egyptian workers.' },
    weavers: { scene: 'scene6', yaw: -21, pitch: -7, title: 'Tomb Painting of Weavers', kicker: 'Craft & technology', image: 'story-images/Scene6-HieroglyphWeavers.jpg', body: 'Egyptian craftspeople developed sophisticated methods for spinning and weaving linen. Tomb art and workshop models preserve a record of this skilled labor.' },
    canopic: { scene: 'scene7', yaw: 38, pitch: -4, title: 'Canopic Jars', kicker: 'The afterlife', image: 'story-images/Scene7-CanopicJars.jpg', body: 'During mummification, selected organs were removed, preserved, and placed in containers now called canopic jars. Their protection was tied to the deceased’s journey into the afterlife.' },
    narmer: { scene: 'scene8', yaw: 66, pitch: 0, title: 'The Narmer Palette', kicker: 'Kingship', image: 'story-images/Scene8-NarmerPalette.jpg', body: 'The Narmer Palette is among the earliest surviving monuments of Egyptian kingship. Its imagery is often connected with the political unification of Upper and Lower Egypt.' },
    color: { scene: 'scene8', yaw: -50, pitch: 8, title: 'A Colorful Egypt', kicker: 'Art & architecture', image: 'story-images/Scene8-Paintings.jpg', body: 'Many Egyptian buildings and statues were originally brightly painted. The bare stone seen today is often only the weathered foundation of a much more colorful design.' },
    pyramids: { scene: 'scene9', yaw: 4, pitch: 5, title: 'The Pyramids', kicker: 'Engineering', image: 'story-images/Scene9-WhitePyramids.jpg', body: 'The great pyramids were carefully planned monuments built by organized teams of skilled workers. Their polished white limestone casing would once have gleamed in the sun.' },
    tools: { scene: 'scene9', yaw: 92, pitch: -13, title: 'Engineering Tools', kicker: 'Technology', image: 'story-images/Scene9-Level.jpg', body: 'Builders used practical tools, measurement, ramps, levers, and large coordinated workforces to shape and position enormous quantities of stone.' }
  }
};
